# [optional] to synchronize time of nodes with 'chrony'
- hosts:
  - kube-master
     [master]
   192.168.254.1
   192.168.254.2
  - kube-node
      [node]
   192.168.254.3
   192.168.254.4
   192.168.254.5
  - etcd
      [etcd]
   192.168.254.6
   192.168.254.7
   192.168.254.8  
  - ex-lb
    [lb]
   192.168.254.1
   192.168.254.2
  - chrony
      [ch]
   192.168.254.1
   192.168.254.2
   192.168.254.3
   192.168.254.4
   192.168.254.5
   192.168.254.6
   192.168.254.7
   192.168.254.8
  roles:
  - { role: chrony, when: "groups['chrony']|length > 0" }

# to create CA, kubeconfig, kube-proxy.kubeconfig etc.
- hosts: localhost
  roles:
  - deploy

# prepare tasks for all nodes
- hosts:
  - kube-master
     [master]
   192.168.254.1
   192.168.254.2
  - kube-node
      [node]
   192.168.254.3
   192.168.254.4
   192.168.254.5
  - etcd
    [etcd]
   192.168.254.6
   192.168.254.7
   192.168.254.8
  roles:
  - prepare

# to install etcd cluster
- hosts: etcd
  roles:
  - etcd
    [etcd]
   192.168.254.6
   192.168.254.7
   192.168.254.8

# to install container runtime
- hosts:
  - kube-master
     [master]
   192.168.254.1
   192.168.254.2
  - kube-node
      [node]
   192.168.254.3
   192.168.254.4
   192.168.254.5
  roles:
  - { role: docker, when: "CONTAINER_RUNTIME == 'docker'" }
  - { role: containerd, when: "CONTAINER_RUNTIME == 'containerd'" }

# to set up 'kube-master' nodes
- hosts: kube-master
  roles:
  - kube-master
      [master]
   192.168.254.1
   192.168.254.2
  - kube-node
     [node]
   192.168.254.3
   192.168.254.4
   192.168.254.5
  tasks:
  - name: Making master nodes SchedulingDisabled
    shell: "{{ bin_dir }}/kubectl cordon {{ inventory_hostname }} "
    when: "inventory_hostname not in groups['kube-node']" 
    ignore_errors: true

  - name: Setting master role name
    shell: "{{ bin_dir }}/kubectl label node {{ inventory_hostname }} kubernetes.io/role=master --overwrite"
    ignore_errors: true

# to set up 'kube-node' nodes
- hosts: kube-node
  roles:
  - { role: kube-node, when: "inventory_hostname not in groups['kube-master']" }

# to install network plugin, only one can be choosen
- hosts:
  - kube-master
      [master]
  192.168.254.1
  192.168.254.2
  - kube-node
      [node]
  192.168.254.3
  192.168.254.4
  192.168.254.5
  roles:
  - { role: calico, when: "CLUSTER_NETWORK == 'calico'" }
  - { role: cilium, when: "CLUSTER_NETWORK == 'cilium'" }
  - { role: flannel, when: "CLUSTER_NETWORK == 'flannel'" }
  - { role: kube-router, when: "CLUSTER_NETWORK == 'kube-router'" }
  - { role: kube-ovn, when: "CLUSTER_NETWORK == 'kube-ovn'" }

# to install cluster-addons
- hosts:
  - kube-node
     [node]
 192.168.254.3
 192.168.254.4
 192.168.254.5
  roles:
  - cluster-addon
